# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /site
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Crossroads.Launcher
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Crossroads
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /test/Crossroads.Launcher.Test
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /test/Crossroads.Test
    schedule:
      interval: daily
